name: Build BOTPLAYER

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:
    name: Build (Android64)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: Android64
          sdk: latest

      - name: Upload hasil build
        uses: actions/upload-artifact@v4
        with:
          name: BOTPLAYER-android64
          path: build/*.geode
